


ej1: Ejercicio1/YodafyClienteTCP.class Ejercicio1/YodafyServidorIterativo.class

ej2: Ejercicio2/YodafyClienteTCP.class Ejercicio2/YodafyServidorIterativo.class


Ejercicio1/YodafyClienteTCP.class: Ejercicio1/YodafyClienteTCP.java
	javac -cp Ejercicio1/ $<

Ejercicio1/YodafyServidorIterativo.class: Ejercicio1/YodafyServidorIterativo.java Ejercicio1/ProcesadorYodafy.java
	javac -cp Ejercicio1/ $<

Ejercicio2/YodafyClienteTCP.class: Ejercicio2/YodafyClienteTCP.java
	javac -cp Ejercicio2/ $<
	
Ejercicio2/YodafyServidorIterativo.class: Ejercicio2/YodafyServidorIterativo.java Ejercicio2/ProcesadorYodafy.java
	javac -cp Ejercicio2/ $<
	
clean:
	rm Ejercicio*/*.class
